apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ldap-proxy-cert
  namespace: {{ .Release.Namespace }}
spec:
  duration: 26280h0m0s
  renewBefore: 720h0m0s
  commonName: ldap-proxy
  dnsNames:
  - ldap-proxy
  - ldap-proxy.{{ .Release.Namespace }}
  - ldap-proxy.{{ .Release.Namespace }}.svc
  - localhost
  issuerRef:
    kind: Issuer
    name: cp4s-issuer
  secretName:  ldap-proxy-cert
